name: Build

on: [ push, pull_request ]

jobs:
  # See https://github.com/dragetd/peercoin/blob/master/doc/build-unix.md#user-content-dependency-build-instructions-ubuntu--debian
  linux:
    strategy:
      matrix:
        platform: [ ubuntu-18.04, ubuntu-20.04 ]
        config: [ minimal, full ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: dependencies
        run: |
          sudo apt-get install -y \
          build-essential libtool pkg-config automake \
          libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev \
          libssl-dev libevent-dev

      - name: additional-dependencies
        if: matrix.config == 'full'
        run: |
          sudo apt-get install -y \
          libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools \
          libqrencode-dev libdb++-dev libprotobuf-dev protobuf-compiler libzmq3-dev libminiupnpc-dev

      - name: build
        if: matrix.config != 'full'
        run: |
          ./autogen.sh
          ./configure --with-incompatible-bdb --without-wallet
          make

      - name: build-full
        if: matrix.config == 'full'
        run: |
          ./autogen.sh
          ./configure --with-incompatible-bdb --with-gui=qt5
          make

